/******SENPAI******/
/*BASE DE DATOS POSTGRESQL*/
/*CREACIÓN DE LA BASE DE DATOS 'sprint9'*/
CREATE ROLE pepito WITH LOGIN PASSWORD 'Rsy7123' SUPERUSER;
ALTER DATABASE sprint9 OWNER TO pepito;
CREATE TABLE PRIORIDAD_DETALLE (
    PRIORIDAD_ID SERIAL NOT NULL,
    NOMBRE VARCHAR NOT NULL,
    DESCRIPCION VARCHAR NOT NULL,
    CONSTRAINT PK_PRIORIDAD_DETALLE PRIMARY KEY (PRIORIDAD_ID)
);
CREATE TABLE USUARIOS (
    USUARIO_ID SERIAL NOT NULL,
    EMAIL VARCHAR NOT NULL,
    ACTIVO BOOLEAN NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIO_ID),
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL)
);
CREATE TABLE LISTA_DE_TAREAS (
    ID SERIAL NOT NULL,
    TITULO VARCHAR NOT NULL,
    PRIORIDAD_ID INTEGER NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    COMPLETADO BOOLEAN,
    CONSTRAINT PK_LISTA_DE_TAREAS PRIMARY KEY (ID)
);
ALTER TABLE LISTA_DE_TAREAS
ADD CONSTRAINT FK_LISTA_DE_TAREAS_PRIO_PRIOTRIDAD_DETALLE_LISTA FOREIGN KEY(PRIORIDAD_ID) REFERENCES PRIORIDAD_DETALLE (PRIORIDAD_ID) on delete restrict on update restrict;
ALTER TABLE LISTA_DE_TAREAS
ADD CONSTRAINT FK_LISTA_DE_TAREAS_USU_USUARIOS_LISTA FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS (USUARIO_ID) on delete restrict on update restrict;
/*INSERCIÓN DE DATOS EN LA BASE*/
INSERT INTO PRIORIDAD_DETALLE (PRIORIDAD_ID, NOMBRE, DESCRIPCION)
VALUES (
        1,
        'Alta',
        'Necesidad de ser cumplida de forma inmediata'
    ),
    (2, 'Media', 'La tarea puede ser aplazada'),
    (3, 'Baja', 'La tarea no es urgente');
INSERT INTO USUARIOS (EMAIL, ACTIVO)
VALUES ('itzae@gmail.com', true),
    ('evelinrodriguez@hotmail.com', true),
    ('pepito@gmail.com', true);
INSERT INTO LISTA_DE_TAREAS (TITULO, PRIORIDAD_ID, USUARIO_ID, COMPLETADO)
VALUES ('Prueba 1', 1, 1, true),
    ('Prueba 2', 1, 1, false);